### ISSUE TITLE
it cant download from danbooru

### ISSUE THREAD

**Issue by KiraiEEE** [nullxception/boorusphere#150] opened 2024-03-04 18:15 UTC
### Type

Booru parser issues

### Bug description

when danbooru selected and you like a pic to download it asks for quality and then doesn't show the downloading progress or even save it so i manually just click the link and get it from the browser 

### Steps to reproduce

1. select danbooru 
2. select any picture
3. click download icon
4. select original or sample
5. (no animation and you get failed notification)

### Android version

android 12

### App version

1.4.2

### Screenshots or videos

![Screenshot_2024-03-04-19-13-03-400_com miui home](https://github.com/nullxception/boorusphere/assets/54278089/63047f9d-0d83-4447-8939-094ada6a1709)

https://github.com/nullxception/boorusphere/assets/54278089/6476946c-a6e1-4ab9-81c6-6f2152ef5a32

### Solution

idk maybe use the link icon value to the downloader 

### Additional context

i hope this get fixed , i love the app and the ui and everything 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by KiraiEEE** [comment] 2024-03-04 18:17
btw the other completed ones are successfully downloaded using safebooru so the problem just with danbooru

**Comment by sadaakisz** [comment] 2024-04-16 00:50
The problem is indeed with Danbooru and how its cdn handles requests with headers.

While taking a look at #149 and scripting a personal solution for downloading all my favorites, I came across a 403 Forbidden when trying to download any image from Danbooru.

[This forum thread](https://danbooru.donmai.us/forum_topics/25845?page=3) indicates some funky business when trying to access content with a program that sends headers that make it look like a browser.

In the end I ended up sending requests without headers when downloading images and had no issues.

It may be worthwhile testing if removing the request headers when downloading from Danbooru solves the issue.

PS: If someone is interested in the fav downloader code, I'll leave it here: [boorusphere_fav_dl](https://github.com/sadaakisz/boorusphere_fav_dl)

**Comment by makisukurisu** [comment] 2024-04-26 09:01
Question for maintainers, perhaps this issue should be closed as a duplicate of #148?

**Comment by makisukurisu** [comment] 2024-04-28 17:49
![image](https://github.com/nullxception/boorusphere/assets/49622129/432112ed-0c38-42e9-a522-f952c2032bd3)

From my tinkering around, sending a request with no headers works just fine. The problem lies in the FlutterDownloader itself, it would seem. (And from debugging tools Flutter provides, its requests are also not visible)

Sadly, it's not possible to see the exact response, but it indeed has a 403 status code. I assume that this sender simply adds some data that doesn't “please” Danbooru → HTTP 403.

**Comment by makisukurisu** [comment] 2024-04-28 18:46
![Response Body](https://github.com/nullxception/boorusphere/assets/49622129/0befd771-0efd-420d-ac44-fcadb85958fc)

After some alterations to the source code of the DownloadWorker, it's now clear that the CDN presents some JS challenge to the downloads class, which it cannot solve.

![Test with cURL](https://github.com/nullxception/boorusphere/assets/49622129/2a7a73da-1011-4759-827e-efa613f73797)
And if you take a look at the source code, the reason is — it's sending a request with a "strange" User-Agent, which (most likely) got banned 😃 

Possible ways of solving the problem:
- Ditch [this](https://github.com/fluttercommunity/flutter_downloader/issues/639) poorly/unsupported library (Way to go, but I suppose — would require a lot of work);
- Add a custom User-Agent property in headers when making a call (something like `Boorusphere/1.0.0` works just fine for now)
- Add authentication support (may not help in this particular case though) as requested in #154 


![Working request](https://github.com/nullxception/boorusphere/assets/49622129/89cf758f-aa0f-4235-b633-28a01040983e)

**Comment by nullxception** [comment] 2024-07-05 18:49
Duplicate of #148

**Closed by nullxception** 2024-07-05 18:49 UTC
Labels: bug
