### ISSUE TITLE
Bug: back button not working

### ISSUE THREAD

**Issue by BigDogg99** [nullxception/boorusphere#68] opened 2022-12-23 12:10 UTC
### Type

UI-related issues

### Bug description

after using search tag from details page of image

### Steps to reproduce

 1. search anything
 2. then try to going back to previous page 

 it dont let me go to previous page

### Android version

11

### App version

latest

### Solution

if pressed back button ,i should go to previous post

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment] 2022-12-31 22:17
Duplicate of #47.
Currently it's not possible to "fix" this due to current data flow design that only focus on single instance search.

**Closed by nullxception** 2022-12-31 22:17 UTC
Labels: bug
