### ISSUE TITLE
Bug: Very laggy app when scrolling, video player and other things

### ISSUE THREAD

**Issue by Palloxin** [nullxception/boorusphere#86] opened 2023-02-12 09:47 UTC
### Type

Other

### Bug description

Scolling post (vertically and horizontally) and video player are very laggy.

### Steps to reproduce

I just go to safebooru and scroll posts

### Android version

a 8 miui 8

### App version

1.2.9

### Screenshots or videos

https://user-images.githubusercontent.com/75091899/218303335-d7c45276-041b-440d-855e-a10f3ff16c77.mp4

### Solution

idk

### Additional context

The bug appears in the ```1.2.7```. Also you have to restore this backup first and then start to scroll
[boorusphere_backup_2023-02-12-10-41-29.zip](https://github.com/nullxception/boorusphere/files/10715763/boorusphere_backup_2023-02-12-10-41-29.zip)
In any case, also without the backup i can notice that the 1.2.7 is not as smooth as the previous versions since there is a little bit of lag while scrolling(1.2.7 and next). If you add the backup the lag is just enchanted. Before the 1.2.7 i never encountered this kind of lag.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Palloxin** [comment] 2023-02-12 09:50
Maybe because i added a lot of tags in the blacklist but in the previous version i never saw that kind of lag, always smooth. I noticed that in the 1.2.7 the backup feature was implemented.

**Comment by nullxception** [comment] 2023-02-12 10:09
have you tried disabling blur ? blur is quite an expensive operation on android (especially on low to mid-end devices)

**Comment by Palloxin** [comment] 2023-02-12 16:08
I never enabled that option. Also the by default it is disabled so when i tested it on other versions i am sure it was disabled too

**Comment by nullxception** [comment] 2023-02-16 06:58
https://user-images.githubusercontent.com/58150791/219290833-b7c1e4fb-9744-47c3-9c48-4f78fbb54b4f.mp4

I tried on emulator with 1.5gb ram and 4 core, no lags while scrolling

**Comment by Palloxin** [comment] 2023-02-16 09:43
my device has 3gb, idk how to emulate it. did you restore from the backup i uploaded?

**Comment by nullxception** [comment] 2023-02-16 10:01
> my device has 3gb, idk how to emulate it. did you restore from the backup i uploaded? With a clean installation(no backup restored, no tags blocked) the lag is very little but still noticeable compared to previous versions of 1.2.7

yes, no issues whatsoever

**Comment by rinme** [comment] 2023-02-16 10:05
> my device has 3gb, idk how to emulate it. did you restore from the backup i uploaded?
> With a clean installation(no backup restored, no tags blocked) the lag is very little but still noticeable compared to previous versions of 1.2.7

I think the problem is device nor Optimize. As I can see it's trying to load a bunch of pictures at the same time that may why it's lagging.

**Comment by nullxception** [comment] 2023-02-16 10:34
> > my device has 3gb, idk how to emulate it. did you restore from the backup i uploaded?
> > With a clean installation(no backup restored, no tags blocked) the lag is very little but still noticeable compared to previous versions of 1.2.7
> 
> I think the problem is device nor Optimize. As I can see it's trying to load a bunch of pictures at the same time that may why it's lagging.


well if it was a device specific issues then nothing we can do except waiting for another flutter update; at least until new rendering engine (Impeller) is stable enough.

**Comment by Palloxin** [comment] 2023-02-16 19:14
Is there a way to send you some kind of log, debug mode or something else that could help you understand how my device operates it?

**Comment by nullxception** [comment] 2023-03-07 10:42
Closing as the issues are not reproducible even on low-spec emulator configuration

**Closed by nullxception** 2023-03-07 10:42 UTC
Labels: bug
